name: CI 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check with linter
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Check style
      run: cargo fmt --all -- --check
    - name: Run tests
      run: cargo test --verbose
